version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  web:
    command: bin/rails server -b '0.0.0.0'
    volumes:
      - .:/rails
    build: .
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - RAILS_ENV=development
    depends_on:
      - db
      - redis
  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:password@db:5432/store_test
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=test
volumes:
  postgres13:
  redis_data:
